
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


CREATE DATABASE IF NOT EXISTS `timeseries` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `timeseries`;
GRANT ALL PRIVILEGES ON timeseries. * TO 'sole'@'%' IDENTIFIED BY 'nostrum';
FLUSH PRIVILEGES;

